baseURL = 'http://www.happymonkeysnowboards.com'
languageCode = 'en-us'
title = 'Monkey Wiki'
theme = 'hugo-book'

disablePathToLower = true

enableGitInfo = true

[frontmatter]
  lastmod = ['dateFromWiki', ':default']

# mmmfixme: how to use, what value?
# copyright = 'Everything is mine'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    contentDir = 'content/en'
    weight = 1
  [languages.zh-cn]
    languageName = '中文（中国大陆）'
    contentDir = 'content/zh-cn'
    weight = 2

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/mikemag/MonkeyWiki"
  weight = 10


[params]
  author = "Mike Magruder"
  description = "How I built snowboards at Happy Monkey Snowboards. Construction techniques, equipment, materials, etc."

  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'MonkeyWiki'
  BookDateFormat = 'Monday January 02, 2006, at 15:04:05 MST'
  BookSearch = false

  xrequire_fancybox = true
